name: Docker Image CI

on:
  push:
    branches:
      - pl.kpherox.dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY,,}/pleroma-kpherox:$(git rev-parse --short HEAD)

    - name: Push the Docker image
      run: |
        docker login docker.pkg.github.com -u ${GITHUB_ACTOR,,} -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/pleroma-kpherox
        docker tag latest docker.pkg.github.com/${GITHUB_REPOSITORY,,}/pleroma-kpherox
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/pleroma-kpherox
